### ISSUE TITLE
Wind speed reported incorrectly

### ISSUE THREAD

**Issue by aeharding** [mivek/MetarParser#413]
**Describe the bug**

Wind speed is reported incorrectly.

**To Reproduce**

Using the following TAF:

```
TAF KLSV 222300Z 2223/2405 21020G35KT 8000 BLDU BKN160 530009 QNH2941INS
  TEMPO 2223/2302 23035G52KT BKN150 560009
  BECMG 2305/2306 35015G25KT 9999 VCSH BKN140 520009 QNH2948INS
  BECMG 2316/2317 34010G18KT 9999 NSW SCT170 QNH2969INS TX28/2323Z TN12/2314Z
```

See wind speed = 0 for the initial TAF conditions, and the first BECMG.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/2166114/197365758-556b4127-49c9-408f-8f3b-ccd29a4150fb.png">

**Expected behavior**

A valid wind speed, see this screenshot for aviationweather.gov's interpretation:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/2166114/197365762-4a084ce7-7629-4862-9e74-5b9c237eabf4.png">

**Additional context**

Appears to be incorrectly matching the turbulence part of the TAF - `530009`.

More info page 29 on turbulence part of TAF http://prnfc.org/wp-content/uploads/2016/12/AF-METAR-TAF-Codes.pdf:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/2166114/197365975-3889926c-74a8-4465-83ff-7a1050cd842b.png">

Thanks you! :)

**Comment by mivek** [comment]
Hello @aeharding 

Your analysis is correct the Wind regex also matches the turbulence so the former value of the wind is erased.

The fix here would be to add the parsing of turbulence and icing. It is not possible to modify the wind regex pattern and force the unit because the unit is not mandatory and falls back on KT.

Here is my suggestion to fix this issue:

- Add a check to prevent the update of the Wind element if it is already present in Metar/TAF
- Add a new object in model "Turbulence" with 3 fields: intensity, base, depth
- Add a new object in model "Icing" with 3 fields: intensity, base, depth.
- Add the corresponding commands

Then if turbulence and icing are also present in METAR :

- Add fields turbulence and icing in [AbstractWeatherCode](https://github.com/mivek/MetarParser/blob/master/metarParser-entities/src/main/java/io/github/mivek/model/AbstractWeatherCode.java).
- Add both commands in the [CommonCommandSupplier](https://github.com/mivek/MetarParser/blob/master/metarParser-parsers/src/main/java/io/github/mivek/command/common/CommonCommandSupplier.java#L39) before the WindCommand.

If the turbulence and icing are only present in TAF

- Create a new package in the command package for TAFs.
- Add the commands and a command supplier.
- Update the [parse ](https://github.com/mivek/MetarParser/blob/master/metarParser-parsers/src/main/java/io/github/mivek/parser/TAFParser.java#L87-L100)method of the TAFParser

This last step is I think the trickiest. I do not want to add more complexity to this method, there are already 4 different conditions in the `for` loop.

I will do some tests and try to find a way to rework the parse method.

We could also split the issue into a bug (for the wind having a wrong value) and a feature (for the parsing of the turbulence and the icing) if the bug is urgent to you.

Let me know what you think of this

**Comment by aeharding** [comment]
Hi @mivek! Thanks for the quick response. This bug is not urgent for me, so I'm fine with either approach (splitting bug + feature or leaving together).

I do agree with you that the best approach would be to make a commands for icing and turbulence and make that have precedence over the wind command. (by the way - from what I've been reading, icing and turbulence seem to be TAF-only)

After thinking a bit more, a potential quick fix is to take advantage of the wind component only starting with a V, 0, 1, 2, or 3 (representing direction - 000-360 or VRB) and the icing/turbulence only starting with a 5 or a 6. By making the wind command regex more strict, this would be the easiest/quickest fix (but maybe not the best... I think command precedence would be the cleanest way to solve the issue.)

Patch I quickly hacked together to test it:

```diff
--- a/src/command/common.ts
+++ b/src/command/common.ts
@@ -99,7 +99,7 @@ export class MainVisibilityCommand implements ICommand {
 }

 export class WindCommand implements ICommand {
-  #regex = /^(VRB|\d{3})(\d{2})G?(\d{2})?(KT|MPS|KM\/H)?/;
+  #regex = /^(VRB|[0-3]\d{2})(\d{2})G?(\d{2})?(KT|MPS|KM\/H)?/;

   canParse(windString: string): boolean {
     return this.#regex.test(windString);
```

But again, this is not an urgent thing for me, so feel free to go with a better/different approach.

**Comment by mivek** [comment]
Hello @aeharding 

I created a PR to fix this issue.
I updated the regex of the Wind as you did in your comment, I also added the parsing of Turbulence and Icing

**Comment by mivek** [comment]
Hello @aeharding 

I merged the PR. I will create a new issue regarding the TAF altimeter group
