### ISSUE TITLE
VCBLSN not being parsed as weather condition

### ISSUE THREAD

**Issue by aeharding** [mivek/MetarParser#432]
**Describe the bug**

`VCBLSN` isn't being parsed as a weather condition

**To Reproduce**

Use METAR `CYVM 282100Z 36028G36KT 1SM -SN DRSN VCBLSN OVC008 M03/M04 A2935 RMK SN2ST8 LAST STFFD OBS/NXT 291200UTC SLP940`, see no `VCBLSN` parsed.

**Expected behavior**

It should parse

**Screenshots**

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/2166114/203430545-a5b93457-1eb1-4939-bca4-b9667ca741ae.png">

**Additional context**

The good news is, with the improved `parseWeatherCondition` function this is a very easy fix - just move that logic above the generic command parser logic (see typescript pull request - https://github.com/aeharding/metar-taf-parser/pull/49/files)

**Comment by mivek** [comment]
Hello @aeharding 

I analyzed the bug, the token `VCBLSN` matches the `CLOUD_REGEX`.
Instead of moving the `parseWeatherCondition`, I prefer to update the `CLOUD_REGEX` so it does not match tokens made of 6 letters.

I will use this regex in the CloudCommand `^([A-Z]{3})((\d{3}|/{3})([A-Z]{2,3}|/{3})?)?$`. The idea is that whenever the cloud type part is present then the height is also present.
